### ISSUE TITLE
PRs should not upload to COVERALLS

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#288]
This came up in #287. The actual `COVERALLS_REPO_TOKEN` Actions secret has the typical restrictions

> Anyone with **collaborator** access to this repository can use these secrets for Actions.
>
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

----

See the "Upload coverage to coveralls" [step][1] in CI.

[1]: https://github.com/dhermes/bezier/blob/ec69f96215e8c0ca55664adc61ec9185e65b372e/.github/workflows/linux.yml#L64-L71

**Comment by dhermes** [comment]
```yaml
    - name: Upload coverage to coveralls
      if: github.event_name != 'pull_request'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        docker exec \
          --env "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" \
          dhermes-bezier \
          ./scripts/upload_coveralls.sh
```
